### ISSUE TITLE
Unable to use LittleLink-Custom : ErrorException

### ISSUE THREAD

**Issue by nashnoor** [JulianPrieber/llc-docker#16]
Hi , I just do a fresh install , and when I try to log in,  it throws me into an error : 

ErrorException
Undefined variable $EventServerExists (View: /htdocs/resources/views/layouts/sidebar.blade.php)
http://173.82.134.137:8086/panel/index

lluminate\Foundation\Bootstrap\HandleExceptions::handleError
resources/views/layouts/sidebar.blade.php:333

  `    <! –– #### begin event detection #### ––>

		<?php

			try {

				function URL_event_exists(string $urlsb): bool

				{

				return str_contains(get_headers($urlsb)[0], "200 OK");

					}

						if (URL_event_exists("https://julianprieber.github.io/littlelink-custom-events/event.json")){

							$EventServerExists = "true";

						}

							} catch (exception $e) {

								$EventServerExists = "false";

							}

						?>

	@if(env('NOTIFY_EVENTS') === true and $EventServerExists == 'true')

        <?php

        $GetEventJson = file_get_contents("https://julianprieber.github.io/littlelink-custom-events/event.json");

		$EventJson = json_decode($GetEventJson, true);

		if(isset($_COOKIE['HideEvent']) == NULL) {

			setcookie("HideEvent",$_COOKIE['ID'] = "0", time()+60*60*24*5, "/");

			    header('Location: ' . url('/panel/index'));

					exit();

					}

		?>

		@if(auth()->user()->role == 'admin' and strtotime(date("d-m-Y")) < strtotime($EventJson['enddate']))

			@if(isset($_COOKIE['HideEvent']) and $_COOKIE['HideEvent'] != $EventJson['id'])

        <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <div class="container-fluid">`

**Comment by MagicLike** [comment]
Thank you for reporting this bug.
We also got the bug ourselves and are trying to figure out how to fix it.
Please be patient.

**Comment by nashnoor** [comment]
I may suggest that the problem may be caused by the url? 

This link returned 404: 
https://julianprieber.github.io/littlelink-custom-events/event.json

**Comment by MagicLike** [comment]
Right, I already opened a PR for that here and I wait for the merge and release: https://github.com/JulianPrieber/littlelink-custom/pull/162

Context for the 404:
We moved the repo and now LLC tries to open the old link...

**Comment by JulianPrieber** [comment]
Fixed https://julianprieber.github.io/littlelink-custom-events/event.json returning an error 404.
