### ISSUE TITLE
PHP version ">= 8.1.0" Needed for Docker Image

### ISSUE THREAD

**Issue by lukeycold** [JulianPrieber/llc-docker#21]
I get an error when I log into the website saying:
```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".
```

**Comment by appuchias** [comment]
Same error here. Using version v2.7.4 made it work for me. It seems the update broke it

**Comment by appuchias** [comment]
Same error here. Also happens after pinning to v2.7.4. Image with sha256:8bc85ffc13e1fce484f73c3151408d19b9f623b82795ea706b8c1e7388388db4 worked until now. Error happened after migrating container to new host and redownloading the image

**Comment by JulianPrieber** [comment]
Just released a fix with: https://github.com/JulianPrieber/littlelink-custom/releases/tag/v2.9.1.

https://hub.docker.com/layers/julianprieber/littlelink-custom/latest/images/sha256-742e0de0958d49143dc2d9d136372658d141645204d6754c6fb4c5042537cbac?context=explore

**Comment by JulianPrieber** [comment]
For existing instances, you should be able to fix this by running:

```
cd /htdocs
composer update
```

From the docker shell.
