### ISSUE TITLE
cannot load [...] due to access control checks

### ISSUE THREAD

**Issue by vquiering** [JulianPrieber/llc-docker#25]
Hi,

I just installed the latest docker image in my homelab which was working like a charm. Awesome tool.

When I installed it on my real world vps behind cloudflare I discovered that adding links is not working anymore. Because of CORS, I guess.

The message in my browser says
`XMLHttpRequest cannot load http://mydomain/studio/linkparamform_part/1/0 due to access control checks.`
while the server says
`"GET /studio/js/bootstrap.min.js.map HTTP/1.1" 404 6609 "https://mydomain/studio/add-link" "client-identifier" 1410 6821`

What can I do to add links again?

**Comment by JulianPrieber** [comment]
Can you access your docker locally and see if that works?

**Comment by vquiering** [comment]
Just tried with the local ip address of the container..... no issue.

**Comment by JulianPrieber** [comment]
Alright. If I understand this correctly, you want to use a reverse proxy and have access to multiple systems to do so?

**Comment by vquiering** [comment]
I want to use cloudflare only as reverse proxy and with their tunnel. Everything else was just a test or troubleshooting.

**Comment by JulianPrieber** [comment]
Hmm, unfortunately we don't have any documentation for that.

However, I personally have a test instance that uses a Cloudflare tunnel with the latest version installed.
There everything works absolutely fine.

### Here is my config:
![screencapture-one-dash-cloudflare-1c36a0358785030a5a0b683d1d772c4c-access-tunnels-public-hostname-edit-2022-11-21-21_59_23 (1)](https://user-images.githubusercontent.com/60265788/203157549-8deac274-af92-4a00-a83c-8676908b72df.png)

**Comment by JulianPrieber** [comment]
The screenshot I attached was made from the setup I'm currently using and have tested.

**Comment by vquiering** [comment]
But thats the tunnel. I am talking about the proxy in Cloudflare.

**Comment by JulianPrieber** [comment]
It has been a while since I set this up. If you're referring to the proxied connection over Cloudflare, I'm using that one as well. I use this for all my instances without problems so far.

![chrome_OKIaIka7md](https://user-images.githubusercontent.com/60265788/203159965-29597ff4-81ba-45cd-81f5-9d9324f3bf4b.png)

**Comment by vquiering** [comment]
I just setup a new instance with a new domain in cloudlfare I haven't used so far. Same issue.
Maybe the apache or php config in the image?

**Comment by JulianPrieber** [comment]
> Maybe the apache or php config in the image?

I mean, that is pretty unlikely. Docker offers a level playing field. If it works for one, it should work for anyone.

**One thing that I have changed is setting my SSL/TLS encryption mode to full.**

![chrome_pZRHb9fscL](https://user-images.githubusercontent.com/60265788/203160726-a255e77f-a0b2-432a-8165-0964624be86a.png)


If you still have any doubts, I would offer you to do some testing on my part. You'd just have to email me the ip and port where I can access your docker instance directly to set up a revere proxy on my end.
You can reach me via this email: [info@littlelink-custom.com](mailto:info@littlelink-custom.com)

**Comment by vquiering** [comment]
I found the culprit. When the `loading.gif` is loaded the code in `/htdocs/resources/views/studio/edit-link.blade.php` doesn't load via https. I hardcoded the https URL to make it work.

**Comment by JulianPrieber** [comment]
Happy you could solve it! I'm marking this as done.
Could you send me your modified `edit-link.blade.php` so I can turn this into a full fix?

**Comment by vquiering** [comment]
I am not a php delevoper and don't know how to properly fix that. This is what it looks like now.

```
    function LoadLinkTypeParams($TypeId, $LinkId) {
        var baseURL = <?php echo "\"" . url('') . "\""; ?>;
	$("#link_params").html(' <img width="70px" src="https://domain.tld/img/loading.gif" />').load(`https://domain.tld/studio/linkparamform_part/${$TypeId}/${$LinkId}`);

    }
```

I guess that `url` is just not resolving to the actual https address. But I don't know how and where.
