### ISSUE TITLE
Header issue with Cloudflared

### ISSUE THREAD

**Issue by Jayavel-S** [JulianPrieber/llc-docker#37]
Hi,

Thank you for your work on this project and for making it accessible through Docker. I have setup the container as per the instructions provided and able to access it through a subdomain using 'Cloudflared'. Since I am using a network connection that does not allow port-forwarding, I am in need to using a service like Cloudflare Tunnels. However, during the initial loading, I am facing the Invalid header configuration issue as mentioned in the repo [here](https://github.com/JulianPrieber/llc-docker#:~:text=Invalid%20header%20configuration).

Can you please assist me with setting up this in a correct way using Cloudflare Tunnels?

**Comment by JulianPrieber** [comment]
This might help you: https://github.com/JulianPrieber/llc-docker/issues/25#issuecomment-1322636588

**Comment by Jayavel-S** [comment]
> This might help you: [#25 (comment)](https://github.com/JulianPrieber/llc-docker/issues/25#issuecomment-1322636588)

Thank you for this. It is now working properly. Awesome work btw!
