### ISSUE TITLE
 Proxy authentication by http header value

### ISSUE THREAD

**Issue by max-tet** [JulianPrieber/llc-docker#4]
When self-hosting Littlelink just for yourself, you might want to have a single point for user management and authentication. It is annoying to login to each and every app seperately.

A pretty simple way to centralize authentication is achieved by deploying apps behind a reverse proxy, and use proxy auth. The proxy handles authentication in some way and sets http headers containing the username that was successfully logged-in. The apps read the headers and associate incoming requests to that user.

The perfect proxy auth feature for me would work like this:

1. Start Littlelink with additional environment variables:

* containing the name of the initial admin user (e.g. admin=admin_user)
* enabling proxy auth (e.g. proxy_auth=true)
* setting the key of the http header that contains the username (e.g. auth_header=X-Authenticated-User)

2. Configure the reverse proxy to authenticate incoming requests in any way you like.
3. Let the reverse proxy set X-Authenticated-User to the authenticated username on every request.
4. Littlelink treats the requests as if they belong to the appropriate user session.
5. Bonus: if Littlelink does not know the username, it creates a new user with that name.

Context: I am using Littlelink for [this product](https://getportal.org/). Since this is a single-user platform, users really should see no login screen at all, not even for SSO.

**Comment by JulianPrieber** [comment]
This would be an interesting addition, however this is probably **outside the scope of this project**.
Implementing such a feature would likely be the enormous effort for me to implement.  I'm not sure if this is something many users would even use. 

As stated in https://github.com/JulianPrieber/llc-docker/issues/4 I can't really afford to have the two LittleLink Custom versions differ from each other. Meaning that this solution had to be implemented in the web version as well.

Despite all this, you or anyone for this matter is welcome to work on this feature, and I'll be happy to implement this in a future update. I'd be happy to assist if there are any question during development.
