### ISSUE TITLE
Add / Edit page not working on Chrome

### ISSUE THREAD

**Issue by chrisjameschamp** [JulianPrieber/llc-docker#47]
I am stuck with this loading on chrome, works fine on firefox.
<img width="376" alt="Screen Shot 2023-03-05 at 11 14 14 AM" src="https://user-images.githubusercontent.com/38870317/222981097-5501b6b1-90d3-4bbb-99fe-e0b79c454cef.png">

Console says its a jquery issue.
![Screen Shot 2023-03-05 at 11 14 28 AM](https://user-images.githubusercontent.com/38870317/222981101-e3df7cba-bcbe-419d-967f-5151dba2bafd.png)

**Comment by JulianPrieber** [comment]
Please try to see if it works when accessing the page directly over whatever ports it's running on without the reverse proxy.

**Comment by chrisjameschamp** [comment]
> 

Same, also my apologies did not realize there was a seperate git for the docker version, I added another issue to the previous one as well that probably needs to be transfered

**Comment by JulianPrieber** [comment]
No problem, I've seen this error a bunch now. In all cases I've seen, I'm sure it's some issue with the reverse proxy setup.
Our team was able to reproduce this error and we were always able to fix it by improving our header setup and forcing everything to use HTTPS.

If some assets are loaded unencrypted, they don't work right.

See:
https://github.com/JulianPrieber/llc-docker/issues/46
https://github.com/JulianPrieber/llc-docker/issues/28
https://github.com/JulianPrieber/llc-docker/issues/38
https://github.com/JulianPrieber/llc-docker/issues/40

We have an example NIGNX reverse proxy example in the README with the correct header setup, if that helps you.

**Comment by chrisjameschamp** [comment]
I will take a look, is it normal that reinstalling the docker deletes all existing data?

**Comment by chrisjameschamp** [comment]
Yup it was an SSL issue, I was port forwarding 80 not 443 but still using https on nginx-proxy-manager
