### ISSUE TITLE
Image resets to default settings

### ISSUE THREAD

**Issue by JulianPrieber** [JulianPrieber/llc-docker#5]
I've noticed that users instances reset to the default settings.

One explanation for this problem would be some system like Watchtower. **However, this does not appear the case, as this happens to users without any form of automatic updates.**

I'm not sure how to approach this or what could be causing this.

### If anyone can find a way to reliably reproduce this issue, please let me know.

**Comment by dnburgess** [comment]
As mentioned in our email conversation, I've had my instance reset and I'm not using WatchTower or any other update solution. Actually I hadn't even run an update on my system when I noticed the container had been reset. Looking forward to a solution when available. :)

**Comment by JulianPrieber** [comment]
I finally got around writing the guide for the persistent storage of the docker.

For me, this is a fairly simple thing that you can essentially do with one extra step. However, I have talked with many people about this and everyone seems to have a different opinion on how to do this.

**If anyone wants to add anything feel free to open a pull request including anything I could have missed.**

**Comment by chrisjameschamp** [comment]
Hey @JulianPrieber I am also having this issue, although I cannot figure out how to add the persistent storage on an Unraid server, any help would be greatly appreciated
