### ISSUE TITLE
Switching to Mysql/MariaDB causes container to not even start

### ISSUE THREAD

**Issue by YouveGotMeowxy** [JulianPrieber/llc-docker#8]
Using the latest container: `julianprieber/littlelink-custom:latest`

When I add this to my Docker compose environment values:

```
      DB_CONNECTION: 'mysql'
      DB_HOST: 'mariadb'
      DB_PORT: '3306'
      DB_DATABASE: 'littlelink'
      DB_USERNAME: 'littlelink'
      DB_PASSWORD: 'redacted'
```

The container crashes on startup (never actually gets running), and shows these errors:

Docker: `Stopped for a few seconds with exit code 137`

Container: `wget: server returned error: HTTP/1.1 500 Internal Server Error`

I have my mariadb container in the same dicker network as the littlelink container, and **_can_** ping it from the LL container's command line.

I don't know if I'm doing this part right, but I was trying to test the connection from the LL c-line directly using:

`jdbc:mariadb:User=littlelink;Password=redacted;Database=littlelink;Server=mariadb;Port=3306;`

gives me a 'User Not Found' error. I've confirmed the user does in fact exist and has priviledges for that db.

Did I screw something up?

**Comment by JulianPrieber** [comment]
Hi,
it appears you're trying to connect your LLC instance to a database. 

Just to make things clear, you do not need an external database for LittleLink Custom. By default, SQLite is used.

If you want to connect to an external database anyway, you will need to do so on the web application itself.
LLC is running on Laravel which has its own environment values which are stored at `/htdocs/.env`.
Luckily, you can just edit this file from the user interface. I recommend using the alternative config editor for this.

There, change `DB_CONNECTION: 'sqlite'` to `mysql` and add your values below.

After that, you will have to seed your database again.
For that, you'll have to run something like:

```
cd /htdocs
php artisan migrate
php artisan db:seed 
php artisan db:seed --class="AdminSeeder"
php artisan db:seed --class="PageSeeder"
php artisan db:seed --class="ButtonSeeder"
php artisan serve
```

Otherwise, no database is needed to run LLC.

Hope this helps 👍

**Comment by YouveGotMeowxy** [comment]
@JulianPrieber 

Hi, tyvm for the super fast reply :)

OK, when I try to do that, I'm able to get up to the last seed (button) and then the container crashes and I cant finish,

Then after the container loads, the .env is reset. I'm going to try copying out the .env, editing locally, and mounting it to the same htdocs folder.

**Comment by JulianPrieber** [comment]
The weakest link is `php artisan db:seed --class="ButtonSeeder"`?

That's very odd. Luckily this one is technically not needed to run LLC, so you could try it without that.

I'm working on adding data persistence to the docks. Here is what I've worked out so far, with this you should be able to keep your .env config even after a full crash:

<br>

1.  Create volume:
`docker volume create llc`

2.  Running the Docker image normally while mounting the volume:
`docker run --detach --name littlelink-custom --publish 80:80 --publish 443:443 --restart unless-stopped --mount source=llc,target=/htdocs julianprieber/littlelink-custom`

This one -> `mount source=llc,target=/htdocs`

_Something like this_

**Comment by JulianPrieber** [comment]
Oh, btw I still have a backup of a MySQL database you can just restore that one to skip seeding the database.
[laravel.sql.gz](https://github.com/JulianPrieber/llc-docker/files/9394887/laravel.sql.gz)

**Comment by YouveGotMeowxy** [comment]
Some progress, but with weird results.

I copied and pasted the contents form the adv editor into a .env file, added my settings, then mounted as:

```
    volumes:
      - '/opt/docker/configs/littlelink/.env:/htdocs/.env:rw'
```

then, white the container was 'starting' (not running fully yet; I use Portainer to be able to tell this) I opened it's c-line and did the migrating/seeding at lightning speed. Time was of the essence here because if I went too slowly during the seeding the container would crash again.

Once I did it all completely, and real fast, it was up and running... BUT.

To check things, I went right to the admin config section and was greeted with a short notice something about malformed utf-8 chars (the notice disappeared very quickly), and then the all the settings in the list wouldn't show like they normally would.

I used a text editor to convert the .env from ANSI to UTF-8 (also tried Unicode), and made sure the line endings were Unix, and restarted the container.

Now it crashes again and won't start. LOL

I don't think I need to use your database because it does connect and seed now, as long as I'm super fast about it.

also, is mounting the entire htdocs folder the proper way? Then all files in that container would be overwritten by my local folder (which may only have the .env in it for now.)

Update:
Just tried switching back to ANSI and it won't start again. LOL

**Comment by JulianPrieber** [comment]
> also, is mounting the entire htdocs folder the proper way? Then all files in that container would be overwritten by my local folder (which may only have the .env in it for now.)

It's the easiest, at least. Essentially, you probably only need the .env file and the config folder, and even that is optional. That's it in your case.

**Comment by YouveGotMeowxy** [comment]
Think I got it!

I dropped all tabled that were previously seeded so it was a blank db again (the seeding/migrating procedure doesn't allow anything but blankness)

then, deleted the previous .env I had, opened a blank text file, converted to unix endings, and UTF-8 while it was all still empty, then pasted the contents again and saved

restarted the container and re-did the seeding (again, at light speed while it was still in the starting phase), and now we're all good!

I can see all the .env config in the UI as usual; changed my admin pw, and restarted the container just to be sure it "stuck" and it did. :)

One thing to note that confused me a lil bit was when I clicked the "change name/email" buttons, absolutely nothing seemed to happen (no feedback whatsoever, so I wasn't sure whether it worked); the "change pw" button also did the same with the exception of the page seeing to refresh and keep my changes. It would be helpful if there were some sort of "change saved" message. :)

Also, perhaps a button to the adv editor right at the top with the others instead of having to scroll all the way down to get to it each time? Just a convenience.

I have one more question, but it's unrelated to this issue, so I'll start a new one in a sec.

**Comment by JulianPrieber** [comment]
> One thing to note that confused me a lil bit was when I clicked the "change name/email" buttons, absolutely nothing seemed to happen (no feedback whatsoever, so I wasn't sure whether it worked)

Yeah, we don't have something like that, rn. It's the same for if it fails or succeeds. I might be able to do something about that with some trickery, but I can't think of something that implements this cleanly.

<br>

> Also, perhaps a button to the adv editor right at the top with the others instead of having to scroll all the way down to get to it each time? Just a convenience.

That's probably a good idea, I will probably squeeze this into the next update.

<br>

> I have one more question, but it's unrelated to this issue, so I'll start a new one in a sec.

Alright 👍 you can go ahead and close this issue if you feel like everything has been resolved.

<br>

> Oops, I forgot to mention above that for some reason now in the UI ir reports that the .env isn't writable:

That's a bit weird, but is probably not a bad thing, as long as you can use the built-in config editor to edit your config.

**Comment by YouveGotMeowxy** [comment]
ok, I fixed the .env thing. It was because when I mount it, it mounts as user 1000:1000. In the container i did a `chown apache:apache .env` and now it's showing as writable again.

**Comment by JulianPrieber** [comment]
> Also, perhaps a button to the adv editor right at the top with the others instead of having to scroll all the way down to get to it each time? Just a convenience.

I settled on including a simple scroll to bottom link:
![chrome_Tsocirfquy](https://user-images.githubusercontent.com/60265788/185955036-fe083ab3-8e71-4b95-9c70-6bf4b9537d22.png)

**Comment by YouveGotMeowxy** [comment]
> That's probably a good idea, I will probably squeeze this into the next update.

Also something I just noticed that's related; it would be more intuitive if the tab bar stayed in place when clicking on any tab after the "upload" tab, as well (rather than disappearing). :)

**Comment by YouveGotMeowxy** [comment]
> I settled on including a simple scroll to bottom link:

I probably didn't explain what I was referring to properly eariler; this is the one I was referring to:

![image](https://user-images.githubusercontent.com/39491297/185956000-5952222e-d58c-4a9c-8980-9ce734ca2f16.png)


although the one you posted is also probably useful as well. :)

To get to that "alternate" editor, you have to always scroll all the way to the bottom just to click it. If it were in the tab bar with the others it would be more convenient.

**Comment by JulianPrieber** [comment]
https://github.com/JulianPrieber/littlelink-custom/commit/250d48a187611f2b8b206878be18605be2442cc6
