### ISSUE TITLE
Reverse Proxy?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [JulianPrieber/llc-docker#9]
I use the [LinuxServer SWAG ](https://hub.docker.com/r/linuxserver/swag)container for reverse proxying and tried to create one for LLC and it partially worked; the site loads, but no CSS:

![image](https://user-images.githubusercontent.com/39491297/185948729-7e12abb0-bcc5-4a1b-8f7d-e7c42ae4d8ed.png)

I've got it pointing to port 80 and all settings seem like they should work.

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name littlelink.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app littlelink-custom;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

Have you ever tried RP'ing this and know the proper settings?

p.s. Sorry to hit you with so many things at once! LOL

**Comment by JulianPrieber** [comment]
No worries.

We got a section in the README for this exact case:

Here is the full thing: https://github.com/JulianPrieber/llc-docker#8

Essentially, you have to do some header magic, so everything gets loaded correctly:

```
server {
listen        443 ssl;
listen        [::]:443 ssl;
listen        80;
listen        [::]:80;
server_name   your.domain.name;


location / {
# Replace with the IP address and port number of your Docker container.
proxy_pass                          [http://127.0.0.1:80](http://127.0.0.1/);
proxy_set_header Host               $host;
proxy_set_header X-Real-IP          $remote_addr;


proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto  https;
proxy_set_header X-VerifiedViaNginx yes;
proxy_read_timeout                  60;
proxy_connect_timeout               60;
proxy_redirect                      off;

# Specific for websockets: force the use of HTTP/1.1 and set the Upgrade header
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_cache_bypass $http_upgrade;
proxy_set_header X-Forwarded-Proto $scheme;

# Fixes Mixed Content errors.
add_header 'Content-Security-Policy' 'upgrade-insecure-requests';

}
}
```

**Comment by YouveGotMeowxy** [comment]
TY, I will play with it later and report back :)

**Comment by YouveGotMeowxy** [comment]
Looks like it worked :)

The only differences from mine were these 2 lines:

```
        proxy_set_header X-VerifiedViaNginx yes;

        # Fixes Mixed Content errors
        add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
```

I've never seen the verifiedbynginx one before; no idea what it does, but 1 or both of those solved it.

**Comment by JulianPrieber** [comment]
I do not really fully understand what it does. 
From what I know, this is It used so that NGINX has verified that the request is legitimate and should be allowed to proceed. This is typically used to prevent malicious requests from reaching upstream servers.

If I'm understanding this right, its just used to make sure that requests coming from NGINX are legitimate.
So I'm not sure why this fixes stuff, but it apparently does 🤷‍♂️.

**Comment by YouveGotMeowxy** [comment]
I just tested by commenting out that nginx line and it still works, so it looks like it was the upgrade insecure requests line.
